# Generated by Django 4.1.1 on 2022-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_databerryuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databerryuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
