# Generated by Django 4.1.1 on 2022-11-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_databerryuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databerryuser",
            name="profile_image",
            field=models.ImageField(default="no_image.png", upload_to="users/"),
        ),
    ]
