# Generated by Django 4.1.3 on 2022-12-01 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteCities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                (
                    "favorite",
                    models.ManyToManyField(
                        blank=None, default=None, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
