# Generated by Django 4.1.1 on 2022-11-10 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteCities",
            new_name="FavoriteCity",
        ),
    ]
