# Generated by Django 4.1.1 on 2022-11-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_city_delete_favoritecity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="user",
            new_name="favourites",
        ),
    ]
